services:
  - type: web
    name: careerforge-backend
    runtime: docker
    plan: free
    region: singapore
    branch: main
    rootDir: carrerforge
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DB_HOST
        fromDatabase:
          name: careerforge-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: careerforge-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: careerforge-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: careerforge-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: careerforge-db
          property: password
      - key: APP_CORS_ALLOWED_ORIGIN
        sync: false
