export const interviewBank = {
  Java: [
    { question: "Explain the four pillars of object-oriented programming.", topic: "Java", expectedKeywords: ["encapsulation", "inheritance", "polymorphism", "abstraction"], modelAnswer: "The four pillars are encapsulation, inheritance, polymorphism, and abstraction. Together they help keep responsibilities clear and make code easier to reuse and change.", acceptedConcepts: { encapsulation: ["encapsulation", "data hiding", "hide state"], inheritance: ["inheritance", "extends", "reuse from a parent"], polymorphism: ["polymorphism", "overriding", "overloading", "many forms"], abstraction: ["abstraction", "abstract", "hide implementation"] } },
    { question: "When would you use a List instead of a Set?", topic: "Java", expectedKeywords: ["duplicates", "insertion order", "unique elements", "collection use case"], modelAnswer: "Use a List when duplicates or predictable insertion order matter and use a Set when each element must be unique. The choice depends on the collection's use case.", acceptedConcepts: { duplicates: ["duplicate", "repeated elements", "same element more than once"], "insertion order": ["insertion order", "ordered", "position", "index"], "unique elements": ["unique", "no duplicates", "distinct"], "collection use case": ["use case", "depends on", "choose based on", "when you need"] } },
    { question: "How do you handle an exception safely?", topic: "Java", expectedKeywords: ["try/catch", "expected exceptions", "validation", "logging", "meaningful error handling"], modelAnswer: "Validate inputs, use try/catch around operations that can fail, catch expected exceptions specifically, log useful context, and return a meaningful error without exposing sensitive details.", acceptedConcepts: { "try/catch": ["try/catch", "try catch", "try block", "catch block"], "expected exceptions": ["expected exception", "specific exception", "catch only", "not catch everything"], validation: ["validation", "validate", "check input"], logging: ["logging", "log the error", "log details"], "meaningful error handling": ["meaningful error", "user-friendly", "safe response", "recover"] } }
  ],
  "Spring Boot": [
    { question: "What problem does dependency injection solve in Spring Boot?", topic: "Spring Boot", expectedKeywords: ["loose coupling", "container", "dependencies", "testing"], modelAnswer: "Dependency injection lets the Spring container provide a class's dependencies, reducing tight coupling and making components easier to replace and test.", acceptedConcepts: { "loose coupling": ["loose coupling", "decouple", "less coupled", "tight coupling"], container: ["container", "spring context", "application context", "bean factory"], dependencies: ["dependency", "dependencies", "inject"], testing: ["test", "testing", "mock"] } },
    { question: "How would you design a REST endpoint in Spring Boot?", topic: "Spring Boot", expectedKeywords: ["controller", "HTTP method", "request mapping", "status code", "DTO"], modelAnswer: "Create a controller with a request mapping and an appropriate HTTP method, validate a request DTO, call a service, and return a suitable response body and status code.", acceptedConcepts: { controller: ["controller", "restcontroller"], "HTTP method": ["get", "post", "put", "delete", "http method"], "request mapping": ["requestmapping", "request mapping", "endpoint route", "path"], "status code": ["status code", "http status", "200", "201", "404"], DTO: ["dto", "data transfer object", "request object"] } },
    { question: "How do you handle errors consistently in a Spring Boot API?", topic: "Spring Boot", expectedKeywords: ["global handler", "exception", "status code", "error response"], modelAnswer: "Use a global exception handler such as ControllerAdvice, map known exceptions to meaningful HTTP status codes, and return a consistent error response without leaking implementation details.", acceptedConcepts: { "global handler": ["controlleradvice", "global exception handler", "exception handler", "global handler"], exception: ["exception", "error"], "status code": ["status code", "http status", "404", "400", "500"], "error response": ["error response", "consistent response", "error body", "problem detail"] } }
  ],
  React: [
    { question: "What is the purpose of state in React?", topic: "React", expectedKeywords: ["component data", "re-render", "change over time", "user interaction"], modelAnswer: "State stores data owned by a component that can change over time. Updating it causes React to re-render the component so the UI reflects user interaction or new data.", acceptedConcepts: { "component data": ["component data", "local data", "component state"], "re-render": ["rerender", "re-render", "render again", "updates the ui"], "change over time": ["change", "over time", "mutable", "update"], "user interaction": ["user interaction", "click", "input", "user action"] } },
    { question: "When does useEffect run?", topic: "React", expectedKeywords: ["after render", "dependency array", "side effect", "cleanup"], modelAnswer: "useEffect runs after a render. Its dependency array controls when it runs again, and it can return a cleanup function for subscriptions, timers, or other side effects.", acceptedConcepts: { "after render": ["after render", "after rendering", "after the component renders"], "dependency array": ["dependency array", "dependencies", "dependency list"], "side effect": ["side effect", "fetch", "subscription", "timer"], cleanup: ["cleanup", "clean up", "return a function", "unsubscribe"] } },
    { question: "How do props support reusable components?", topic: "React", expectedKeywords: ["parent to child", "input", "reusable", "data or behavior"], modelAnswer: "Props are read-only inputs passed from a parent to a child. They let the same component render different data or behavior without duplicating the component's implementation.", acceptedConcepts: { "parent to child": ["parent to child", "parent passes", "passed from parent"], input: ["input", "parameter", "argument"], reusable: ["reusable", "reuse", "different data"], "data or behavior": ["data", "behavior", "callback", "function"] } }
  ],
  SQL: [
    { question: "What is the difference between WHERE and HAVING?", topic: "SQL", expectedKeywords: ["before grouping", "after grouping", "aggregate", "filter"], modelAnswer: "WHERE filters individual rows before GROUP BY, while HAVING filters grouped results after aggregation and can use aggregate conditions such as COUNT or SUM.", acceptedConcepts: { "before grouping": ["before group", "before grouping", "where filters rows"], "after grouping": ["after group", "after grouping", "having filters groups"], aggregate: ["aggregate", "count", "sum", "average", "avg"], filter: ["filter", "condition", "predicate"] } },
    { question: "Why do we use a foreign key?", topic: "SQL", expectedKeywords: ["relationship", "referential integrity", "another table", "matching row"], modelAnswer: "A foreign key links a column to a key in another table, represents a relationship, and helps enforce referential integrity so references point to valid rows.", acceptedConcepts: { relationship: ["relationship", "relate", "link"], "referential integrity": ["referential integrity", "integrity", "valid reference"], "another table": ["another table", "parent table", "referenced table"], "matching row": ["matching row", "existing row", "primary key"] } },
    { question: "Describe an INNER JOIN.", topic: "SQL", expectedKeywords: ["two tables", "matching rows", "join condition", "only matches"], modelAnswer: "An INNER JOIN combines two tables using a join condition and returns only rows where the join keys match in both tables.", acceptedConcepts: { "two tables": ["two tables", "tables"], "matching rows": ["matching rows", "matching records", "same key"], "join condition": ["join condition", "on clause", "join key"], "only matches": ["only matches", "only matching", "intersection"] } }
  ],
  "HTML & CSS": [
    { question: "How do semantic HTML elements improve a page?", topic: "HTML & CSS", expectedKeywords: ["meaning", "accessibility", "structure", "search engines"], modelAnswer: "Semantic elements communicate the meaning and structure of content, improving accessibility for assistive technologies and helping search engines understand the page.", acceptedConcepts: { meaning: ["meaning", "semantic", "purpose"], accessibility: ["accessibility", "screen reader", "assistive technology"], structure: ["structure", "header", "main", "nav", "section"], "search engines": ["search engine", "seo", "crawling"] } },
    { question: "How does CSS specificity determine which rule wins?", topic: "HTML & CSS", expectedKeywords: ["selector", "specificity", "id", "class", "source order"], modelAnswer: "The browser compares selector specificity, with inline styles and IDs generally outweighing classes and element selectors; when specificity ties, the later rule wins.", acceptedConcepts: { selector: ["selector", "css rule"], specificity: ["specificity", "specific"], id: ["id", "#"], class: ["class", ".class"], "source order": ["source order", "later rule", "last rule"] } },
    { question: "What is responsive web design?", topic: "HTML & CSS", expectedKeywords: ["screen size", "media query", "flexible layout", "mobile"], modelAnswer: "Responsive design adapts a flexible layout and content to different screen sizes, commonly using fluid dimensions, flexible grids, and media queries for mobile and desktop.", acceptedConcepts: { "screen size": ["screen size", "viewport", "device"], "media query": ["media quer", "breakpoint"], "flexible layout": ["flexible", "fluid", "flexbox", "grid"], mobile: ["mobile", "desktop", "different devices"] } }
  ],
  Git: [
    { question: "What is the difference between git merge and git rebase?", topic: "Git", expectedKeywords: ["combine histories", "merge commit", "linear history", "rewrite history"], modelAnswer: "Both integrate branches. Merge preserves the divergent history and may create a merge commit, while rebase replays commits onto a new base to create a linear history and rewrites commit history.", acceptedConcepts: { "combine histories": ["combine", "integrate", "join branches"], "merge commit": ["merge commit", "preserve history"], "linear history": ["linear history", "straight history", "onto a base"], "rewrite history": ["rewrite history", "replay commits", "rewrites"] } },
    { question: "How do you resolve a Git merge conflict safely?", topic: "Git", expectedKeywords: ["inspect conflict", "choose changes", "test", "stage", "commit"], modelAnswer: "Inspect the conflicted files, choose or combine the intended changes, remove conflict markers, run tests, stage the resolved files, and complete the merge commit.", acceptedConcepts: { "inspect conflict": ["inspect", "conflict", "git status"], "choose changes": ["choose", "combine", "ours", "theirs", "resolve"], test: ["test", "tests", "build"], stage: ["stage", "git add"], commit: ["commit", "merge commit"] } },
    { question: "Why should commits be small and descriptive?", topic: "Git", expectedKeywords: ["review", "revert", "history", "focused change"], modelAnswer: "Small, descriptive commits keep each change focused, make history easier to review and understand, and make it safer to revert or isolate a problem.", acceptedConcepts: { review: ["review", "code review"], revert: ["revert", "undo", "rollback"], history: ["history", "log", "understand changes"], "focused change": ["focused", "small change", "single change"] } }
  ]
};

const normalize = (value) => value.toLowerCase().replace(/[^a-z0-9+#/. -]/g, " ").replace(/\s+/g, " ").trim();

export function evaluateAnswer(question, answer) {
  const normalized = normalize(answer || "");
  const matchedConcepts = question.expectedKeywords.filter((concept) => {
    const aliases = question.acceptedConcepts?.[concept] || [concept];
    return aliases.some((alias) => normalized.includes(normalize(alias)));
  });
  const missingConcepts = question.expectedKeywords.filter((concept) => !matchedConcepts.includes(concept));
  const ratio = matchedConcepts.length / question.expectedKeywords.length;
  const points = ratio >= 0.75 ? 3 : ratio >= 0.5 ? 2 : ratio > 0 ? 1 : 0;
  const label = points === 3 ? "Strong answer" : points === 2 ? "Good answer" : points === 1 ? "Partial answer" : "Needs improvement";
  const explanation = matchedConcepts.length
    ? `Your answer mentioned ${matchedConcepts.join(", ")}${missingConcepts.length ? `, but did not address ${missingConcepts.join(", ")}.` : "."}`
    : "Your answer did not mention the key concepts needed to address this question.";
  return { points, percentage: Math.round(ratio * 100), label, explanation, matchedConcepts, missingConcepts };
}
